<a href="https://colab.research.google.com/github/AnshuPali276/DAVIS_Claas_work/blob/main/ZerosArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# array creation in numpy
import numpy as np
array3=np.zeros((3,5))
print(array3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
array4=np.zeros((4,5), dtype='int')
print(array4)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
